### ISSUE TITLE
Chromosonia with fluxus 019

### ISSUE THREAD

**Issue by yangh** [gaborpapp/Chromosonia#1]
Hi Gabor

I found Chromosonia via the racket-users mail list, and trying to run it with fluxus 019 [1] + Racket 7.4, after installing some staffs, it works. but I'm not sure if the visualization is correct as design, could you please help to check the attached screenshot and comment on it. BTW, I have no access to the video you posted on the Vimeo, so I can't confirm it by my self.

Chromosonia is very cool.

Thanks

[1] https://gitlab.com/nebogeo/fluxus

/Chromosonia$ fluxus -x chromosonia.scm

![Screenshot from 2019-10-08 20-07-48-chromosonia-visual-2](https://user-images.githubusercontent.com/48126/66457801-c0febe80-eaa3-11e9-95aa-9e9888e30ac9.png)

Chromosonia/facade-control$ fluxus -x perceptual.scm
![Screenshot from 2019-10-09 14-43-33-fc-perceptual](https://user-images.githubusercontent.com/48126/66457808-c4924580-eaa3-11e9-828d-f1e1cb476d63.png)

**Comment by gaborpapp** [comment]
Hi,

Congratulations. I didn't think it would be possible to install it after
these many years. It looks ok as far as I can tell. Maybe it will look
better if more music are played to it.

**Comment by yangh** [comment]
Hi Gabor

It good to hear from you, as the project has no update after these many years, same to fluxus. I managed to get fluxus to run with the latest racket, played with the fluxus-audio module for a while, so its not that hard for me to run Chromosonia again:) chromosonia-audio takes samiliar approch to capture audio stream, the main different part is the algorithm used for visualizing the acoustics: sonotopy (which also has no update since 2013).

All in all , Chromosonia is a pretty good application to demo what fluxus can do.

One more question, do the small black squares and black triangle in the screenshot is normal?

![Screenshot from 2019-10-09 23-52-11-fc-3](https://user-images.githubusercontent.com/48126/66498044-0517b080-eaf0-11e9-8b31-17526c09633c.png)

Thanks again

**Comment by gaborpapp** [comment]
Dave has recently updated fluxus here:
https://gitlab.com/nebogeo/fluxus

As far as I remember the black pixels are not normal, because it should be a smooth transition, but I can be wrong. Try to send songs with various genre to it. Maybe it gives a hint if you see what happens when different colors meet.

**Comment by yangh** [comment]
Got it, thanks

**Comment by yangh** [comment]
Thanks
